server:
  port: 8088
spring:
  datasource:
    password: sparc
    url: jdbc:postgresql://localhost:5432/healthex
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
